apiVersion: v1
kind: Service
metadata:
  name: clean-marvel
  labels:
    app: clean-marvel
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: clean-marvel
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
