apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clean-marvel-web
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: clean-marvel.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clean-marvel
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clean-marvel-rag
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /rag/$2
spec:
  ingressClassName: nginx
  rules:
    - host: clean-marvel.local
      http:
        paths:
          - path: /api/rag(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: rag-service
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clean-marvel-openai
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: clean-marvel.local
      http:
        paths:
          - path: /api/openai(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: openai-service
                port:
                  number: 8081
